### PR TITLE
Avoid extra newlines

### PR DESCRIPTION
**Pull request by shaperilio**
Moved the newline before each section into the conditional blocks of the included templates. Otherwise, if an intermediate section is not present, you'll get extra newlines between those that are.

### CODE REVIEW

**Comment by NilsJPWerner** [comment]
Sorry for the delay in checking this. Can you rebase master so we can see the github actions tests?

**Comment by shaperilio** [comment]
Done!

**Comment by NilsJPWerner** [comment]
Are you sure, I don't see the workflows in your branch

**Comment by shaperilio** [comment]
Sorry, I did it on the wrong branch :)

**Pull request merged**
