### PR TITLE
Match async functions/methods

### PR DESCRIPTION
**Pull request by crdil**
Match async functions/methods

### CODE REVIEW

**Comment by Modelmat** [comment]
This doesn't appear to be fixed. Unless it hasn't be uploaded yet.

**Comment by NilsJPWerner** [comment]
Was merged after the most recent update.

**Comment by Modelmat** [comment]
Ok. It'll be fixed in next one?

**Comment by NilsJPWerner** [comment]
Yeah, I'll push it with the improved parser I've been working on and the
other docstring formats.

On January 2, 2018 at 10:32:14 PM, Modelmat (notifications@github.com)
wrote:

Ok. It'll be fixed in next one?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/NilsJPWerner/autoDocstring/pull/8#issuecomment-354880638>,
or mute the thread

**Pull request merged**
