### PR TITLE
Fixes #143: Ignore "raise something" in comments

### LINKED ISSUE #143: If a commented piece of code contains the word "raise" docstring tries to parse it.
**Describe the bug**
I had a function in which I had a `# TODO:` comment that was `raise appropriate error`

When generating the docstring it was parsed as if I was declaring an Exception 😂. Pretty funny corner case! 

Running 0.5.3

**Original Code (with line to generate on):**
```python
def foo(bar):
	print('Hello World')
	# TODO: raise appropriate error down the line
```

**Expected Result:**
```python
def foo(bar):
    """[summary]

    Args:
        bar ([type]): [description]
    """
	print('Hello World')
	# TODO: raise appropriate error down the line
```

**Actual Result:**
```python
def foo(bar):
    """[summary]

    Args:
        bar ([type]): [description]

    Raises:
        appropriate: [description]
    """
	print('Hello World')
	# TODO: raise appropriate error down the line
```

### PR DESCRIPTION
**Pull request by bastienboutonnet**
# Aim
I found a bug (reported in #143 ) where if you have some commented out sentence that contains the word "raise" would cause it to be parsed as if it was an Exception leading to this strange behaviour:
```python
def foo(bar):
    """[summary]

    Args:
        bar ([type]): [description]

    Raises:
        appropriate: [description]
    """
	print('Hello World')
	# TODO: raise appropriate error down the line
```

I modified the regex pattern to ignore raise if a "#" came at any point before it.

# How was this tested
Ran the example snippet provided above with expected behaviour. Ran it also with a good old Exception to see if I didn't just break the functionality all together
`npn run test` & `npm run integration_test` 

I didn't add a test to cover this particular case (I figured better to leave the current test be simple), but if you feel strongly about it I could!

# Related Issue
Fixes #143

### CODE REVIEW

**Comment by NilsJPWerner** [comment]
I think a more universal solution would be to filter out lines in the body that start with "#". I did this in the getDefinition function: https://github.com/NilsJPWerner/autoDocstring/blob/master/src/parse/get_definition.ts#L34 If we do something similar in the getBody function we don't have to worry about it in later steps.

**Comment by NilsJPWerner** [comment]
We could add to this condition: https://github.com/NilsJPWerner/autoDocstring/blob/master/src/parse/get_body.ts#L13

**Comment by bastienboutonnet** [comment]
Yeah that would make sense. Would it be a problem if someone were to write an inline comment though?

**Comment by bastienboutonnet** [comment]
I agree with you that it might bet better to solve the case earlier in the flow rather than on a per method basis but if someone were to write an inline comment we'd hit out head again. Is there something else we can do?

**Comment by NilsJPWerner** [comment]
We could strip inline comments as well. They will never need to be parsed I think.

**Comment by bastienboutonnet** [comment]
How would you think of doing that? Split the line upon finding `#` in a line and discard the second part? Ignore any line that contains the hash? 

If so, then you'd have an issue if `#` is used in the code maybe as part of a string or so.

But maybe I'm not seeing something else to do that would be obvious and simple?

**Comment by HaaLeo** [comment]
@NilsJPWerner  @bastienboutonnet I proposed a more general approach for #143 in #146. 
But the PR will only fix #143 not the more complex scenarios you discussed here or like the sample I mention in #146 .

**Comment by bastienboutonnet** [comment]
Cool yeah I meant to look into how to cater for inline comments also. But I haven't had a chance

**Comment by HaaLeo** [comment]
I think to also handle inline comments is super difficult, if not impossible without semantic information.
Imagine something like:
```python
def foo():
    print('# I am not a comment') # But I am one
```

**Comment by NilsJPWerner** [comment]
I've been basing a lot of parsing on the magic python patterns. Might be worth looking into how they parse inline comments using regex: https://github.com/microsoft/vscode-python/blob/4f774d94bf4fbf87bb417b2b2b8e79e334eb3536/resources/MagicPython.tmLanguage.json#L59

**Comment by bastienboutonnet** [comment]
I looked a bit more into it and tried many (MANY) regexes. I am not the best with them but it does seem like it will be pretty hard to find a genetic solution for all the cases. 

I also looked at the link but I can't really understand how they do what they do and if it applies. What is it supposed to power?

Here are a few things to consider:

1. The following (albeit a bit awkward) pattern will work: 
`/(?<![\'\"\w][\s-!$%^&*_+|~=`{}\[\]:";'<>?,.\/]*)\#(.*)/`
```python
def foo():
	print(' I # am not a comment') # but I am

def foo():
	print(' I'm not a 1,?- # comment') # but I am
```
2. but it will fail for something like this

```python
def foo():
	1 + 12 # I raise a comment
```

My feeling is, while it's nice to find a generic solution, sometimes abstraction isn't your friend. And here unless we were using an actual parser rather than regexes it probably wouldn't work...

As much as I love abstraction and generic solutions, I would say that actually here the less generic solution proposed would achieve what the actual goal of the functionality is and for lack of better solution (if any) it is still a very suitable solution.

This could be coupled with a generic stripping of comment lines of course as these would cover 99% of the cases.

Depends what the priority is here...

**Comment by NilsJPWerner** [comment]
I agree. I will merge both prs to get the benefit of both of them. @bastienboutonnet can you add one unit test to cover the situation with the inline raise comment.

Thank you both for you contributions. I really appreciate it!

**Comment by bastienboutonnet** [comment]
Awesome I'll aim to write that test asap! And no worries always happy to help

**Comment by bastienboutonnet** [comment]
@NilsJPWerner I added a test, not sure if it's sufficient though so let me know if I can do better.

**Pull request merged**
